### ISSUE TITLE
work on getting data from new source

### ISSUE THREAD

**Issue by moarshy** [AlgoveraAI/chainlink-assistant#2]
New source
https://data.chain.link/ 
eg: https://data.chain.link/ethereum/mainnet/crypto-usd/eth-usd 

1. read data
2. convert to simple English

Potential questions asked by devs
- check if a feed is verified, ex: Is eth/usd a verified feed?
- is eth/usd feed backed by staking?
- under what asset class does eth/usd fall?
- what is the tier of the eth/usd feed on binance?
- what is the deviation threshold of eth/usd on binance?
- how many oracles carry eth/usd on binance?
(replace asset and blockchain name by any combination)

**Comment by hithesh98** [comment]
@moarshy What is the progress on this?

**Comment by richardblythman** [comment]
@hithesh98 ICYMI https://algovera.slack.com/archives/C05LW70BYBS/p1692106276614909?thread_ts=1691583288.735829&cid=C05LW70BYBS
