### ISSUE TITLE
Basic keyword search for deliverable 2

### ISSUE THREAD

**Issue by moarshy** [AlgoveraAI/chainlink-assistant#3]

**Comment by richardblythman** [comment]
From my conversation with @moarshy on Slack:

LangChain has some hybrid search so maybe we can just use something like that out of the box. Part of the hybrid is semantic, but the other is keyword. TF-IDF the keyword part. 

Chainlink only asked for was keyword search, so let's see if we can simply use LangChain without the semantic part.
